//created on: 12/02/2016
package com.sample.reglas

//list any import classes here.

import com.sample.model.*;



//declare any global variables here




rule "Regla de prueba"
    when
        Cliente(edad < 21)
        venta : Venta(montoTotal > 100, recargos == 0)
    then
        venta.setRecargos(new java.math.BigDecimal(50.00));
        System.out.println("Se disparó la regla");
end


rule "regla de prueba 2"

  when
    Cliente(edad > 21)
    then
       System.out.println("Se disparó la otra regla");

end